config/routes.rb
MatomeChannel::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :members, only: [] do
    member do
      get "board_favorites"
      get "summary_favorites" 
      get 'boards'
      get 'summaries'
    end
  end

  resources :categories, only: [] do
    member do
      resources :boards, as: :category_boards , only: [:index, :new] do
        collection do
          match "t/:tag_id" => "boards#tag", as: :tag, via: :get
        end
      end
      resources 'summaries', as: :category_summaries, only: [:index] do
        collection do
          match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
        end
      end
    end
  end

  resources :boards, only: [:index, :show, :new, :create]do
    collection do
      match "t/:tag_id" => "boards#tag", as: :tag, via: :get
    end
    member do
      match 'comments/:num' => "boards#comments", as: :comments, via: :get
      match 'websites/:num' => "boards#websites", as: :websites, via: :get
      match 'images/:num' => "boards#images", as: :images, via: :get
      match 'movies/:num' => "boards#movies", as: :movies, via: :get
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
  end

  resources :comments, only: [:show,:create] do
    member do
      post :good
      post :bad
      post :ng, :action => :add_ng
      delete :ng, :action => :remove_ng
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
    resources :t, controller: "comment_tags", except: [:index, :edit, :update]
  end

  resources :websites, only: [] do
    member do
      get :thumb
    end
  end

  resources :images, only: [:create] do
    member do
      get :image
      get :thumb
    end
  end

  resources :movies, only: [] do
    member do
      get :animation
      get :thumb
    end
  end

  resources :summaries, except: [:new, :destroy] do
    collection do
      match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
      match 'new/:board_id' => 'summaries#new', via: :get, as: :new
      post 'items'
    end
  end

  resources :favorites, only: [:index, :destroy] do
    collection do
      get 'boards'
      get 'summaries'
      post 'boards', action: :create_board
      post 'summaries', action: :create_summary
      delete 'boards/:id', action: :destroy_board
      delete 'summaries/:id', action: :destroy_summary
    end
  end

  scope 'my' do
    get 'boards', controller: "histories", action: "my_boards", as: :my_boards
    get 'comments', controller: "histories", action: "my_comments", as: :my_comments
    get 'summaries', controller: "histories", action: "my_summaries", as: :my_summaries
  end

  scope 'histories' do
    get 'boards', controller: "histories", action: "boards", as: :boards_history
    get 'summaries', controller: "histories", action: "summaries", as: :summaries_history
  end

  resource :ng_list, only: [:show]
  resource :check_list, only: [:show]
  resources :tags, only: [] do
    collection do
      get 'board'
      get 'summary'
      get 'observe', action: :observe
    end
  end

  root :to => 'top#index'

  match '*a', :to => 'application#error_404'

end

app/models/website.rb
class Website
  include Mongoid::Document
  include Mongoid::Timestamps
  include Storable

  storable_on :thumb

  # fields
  field :url, type: String
  field :title, type: String

  # relation
  has_and_belongs_to_many :comments

  # indexes
  index({ url: 1 }, { name: "url_index" })

  def to_thumb_html
    get_view.render(
      :partial => "websites/thumb",
      :locals => {:website => self})
  end

  def to_html
    get_view.render(
      :partial => "websites/website",
      :locals => {:website => self})
  end

  def hash_ids
    self.comments.map(&:hash_id).uniq
  end

  private
  def get_view
    view = ActionView::Base.new(Rails.configuration.paths["app/views"].first)
    class << view
      include WebsitesHelper
      include Rails.application.routes.url_helpers
    end
    view
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  def thumb
    website = Website.find(params[:id])
    if Settings.mogilefs.nginx_proxy
      response.header["Content-Type"] = "image/png"
      response.header["X-Accel-Redirect"] = "/reproxy"
      response.header["x-reproxy-url"] = website.thumb_paths.sample
      render nothing: true
    else
      send_data website.thumb, :type => "image/png", :disposition => 'inline'
    end
  end

end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/websites/_list.html.erb
<div id='websites-container' class='container tab-pane'>
  <ul id='website-list' class="thumbnails">
    <%= render partial: 'websites/website', collection: websites.map(&:website) %>
  </ul>
  <% if websites.size >= BoardWebsite::COUNT_PER_PAGE %>
  <div id="website-pagination" class="well" style="text-align:center">
    <%= link_to "続きを見る", websites_board_path(
      id: websites.last.board_id,
      num: "-#{websites.last.id}"
    ) %>
  </div>
  <% end %>
</div>

app/views/websites/_thumb.html.erb
<div class="clearfix website-thumb pull-left">
  <div class="title">
    <%= link_to website.title.cut(10), website.url, title:  website.title  %>
  </div>
  <%= link_to website.url, class: "thumbnail", :target => "_BLANK" do %>
    <%= image_tag thumb_website_path(website), :title => website.title %>
  <% end %>
</div>

app/views/websites/_website.html.erb
<li class="website span3" data-hash-ids="<%= website.hash_ids.join(",") %>" data-type='ok'>
  <div class="well ok-website">
    <%= link_to website.url, class: "thumbnail", target: "_BLANK" do %>
      <%= image_tag thumb_website_path(website) %>
    <% end %>
    <h4><%= link_to website.title.to_s, website.url, target: "_BLANK" %></h4>
  </div>
  <div class="well ng-website">
    <%= image_tag 'placeholder.png', class: "placeholder thumbnail" %>
    <h4>NGだよ！</h4>
  </div>
</li>