config/routes.rb
MatomeChannel::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :members, only: [] do
    member do
      get "board_favorites"
      get "summary_favorites" 
      get 'boards'
      get 'summaries'
    end
  end

  resources :categories, only: [] do
    member do
      resources :boards, as: :category_boards , only: [:index, :new] do
        collection do
          match "t/:tag_id" => "boards#tag", as: :tag, via: :get
        end
      end
      resources 'summaries', as: :category_summaries, only: [:index] do
        collection do
          match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
        end
      end
    end
  end

  resources :boards, only: [:index, :show, :new, :create]do
    collection do
      match "t/:tag_id" => "boards#tag", as: :tag, via: :get
    end
    member do
      match 'comments/:num' => "boards#comments", as: :comments, via: :get
      match 'websites/:num' => "boards#websites", as: :websites, via: :get
      match 'images/:num' => "boards#images", as: :images, via: :get
      match 'movies/:num' => "boards#movies", as: :movies, via: :get
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
  end

  resources :comments, only: [:show,:create] do
    member do
      post :good
      post :bad
      post :ng, :action => :add_ng
      delete :ng, :action => :remove_ng
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
    resources :t, controller: "comment_tags", except: [:index, :edit, :update]
  end

  resources :websites, only: [] do
    member do
      get :thumb
    end
  end

  resources :images, only: [:create] do
    member do
      get :image
      get :thumb
    end
  end

  resources :movies, only: [] do
    member do
      get :animation
      get :thumb
    end
  end

  resources :summaries, except: [:new, :destroy] do
    collection do
      match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
      match 'new/:board_id' => 'summaries#new', via: :get, as: :new
      post 'items'
    end
  end

  resources :favorites, only: [:index, :destroy] do
    collection do
      get 'boards'
      get 'summaries'
      post 'boards', action: :create_board
      post 'summaries', action: :create_summary
      delete 'boards/:id', action: :destroy_board
      delete 'summaries/:id', action: :destroy_summary
    end
  end

  scope 'my' do
    get 'boards', controller: "histories", action: "my_boards", as: :my_boards
    get 'comments', controller: "histories", action: "my_comments", as: :my_comments
    get 'summaries', controller: "histories", action: "my_summaries", as: :my_summaries
  end

  scope 'histories' do
    get 'boards', controller: "histories", action: "boards", as: :boards_history
    get 'summaries', controller: "histories", action: "summaries", as: :summaries_history
  end

  resource :ng_list, only: [:show]
  resource :check_list, only: [:show]
  resources :tags, only: [] do
    collection do
      get 'board'
      get 'summary'
      get 'observe', action: :observe
    end
  end

  root :to => 'top#index'

  match '*a', :to => 'application#error_404'

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_filter :authenticate_user!

  def boards
    @user = current_user
    @favorites = current_user.board_favorites.order_by(created_at: :desc).page(params[:page]).per(20)
  end

  def summaries
    @user = current_user
    @favorites = current_user.summary_favorites.order_by(created_at: :desc).page(params[:page]).per(20)
  end

  def create_board
    board = Board.find params[:board_id]
    favorite = BoardFavorite.new{|f|f.board = board}
    current_user.board_favorites << favorite
    board.notify_change_favorites
    render :json => {id: favorite.id}
  end

  def create_summary
    summary = Summary.find params[:summary_id]
    favorite = SummaryFavorite.new{|f|f.summary = summary}
    current_user.summary_favorites << favorite
    render :json => {id: favorite.id}
  end

  def destroy_board
    favorite = BoardFavorite.find params[:id]
    board = favorite.board
    favorite.destroy
    board.reload.notify_change_favorites
    render :json => {result: :ok}
  end

  def destroy_summary
    favorite = SummaryFavorite.find params[:id]
    summary = favorite.summary
    favorite.destroy
    render :json => {result: :ok}
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/boards.html.erb
<h1><%= @user.name %>さんのお気に入り一覧</h1>
<hr>
<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#boards-favorites" data-toggle="tab">スレッド</a></li>
  <li><%= link_to "まとめ", summaries_favorites_path %></li>
</ul>

<div class="clearfix tab-content">
  <div class="boards" class="tab-pane active" style="margin-left:15px;">
    <%= render partial: "boards/board", collection: @favorites.map(&:board), as: :board %>
  </div>
</div>
<hr>
<div align="center">
<%= paginate @favorites %>
</div>

app/views/favorites/summaries.html.erb
<h1><%= @user.name %>さんのお気に入り一覧</h1>
<hr>
<ul class="nav nav-tabs" id="myTab">
  <li><%= link_to "スレッド", boards_favorites_path %></li>
  <li class="active"><a href="#summaries-favorites" data-toggle="tab">まとめ</a></li>
</ul>
<div class="clearfix tab-content">
  <%= render partial: "summaries/summary", collection: @favorites.map(&:summary) %>
</div>

app/views/favorites/summaris.html.erb
<h1><%= @user.name %>さんのお気に入り一覧</h1>
<hr>
<div class="clearfix">
<% @favorites.map(&:board).each do |board| %>
  <div class="thread-container span3 well" style="margin-left:15px;">
    <div class="thread-content">
      <div class="total">
        <span class="badge board-score" title="スコア">
          <i class='icon-star icon-white'></i>
          <strong><%= board.score %></strong>
        </span>
        <span class="badge res-count" title="レス数">
          <i class='icon-pencil icon-white'></i>
          <strong><%= board.count %></strong>
        </span>
        <span class="badge favorites-count" title="お気に入り登録数">
          <i class='icon-heart icon-white'></i>
          <strong><%= board.favorites.count %></strong>
        </span>
      </div>
      <h4 class="title">
        <%= link_to board.title.to_s.cut(50), board, title:  board.title  %>
      </h4>
      <%= link_to board_path(board), class: :thumbnail do %>
        <%= image_tag thumbnail_path(board.thumbnail) %>
      <% end %>
      <p class='first-comment'>
        <%= board.first_comment.try(:body).to_s.cut(290) %>
      </p>
      <div class='tag-list'>
        <%= tag_list board.tags %>
      </div>
    </div>
  </div>
<% end %>
</div>
<hr>
<div align="center">
<%= paginate @favorites %>
</div>