config/routes.rb
MatomeChannel::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :members, only: [] do
    member do
      get "board_favorites"
      get "summary_favorites" 
      get 'boards'
      get 'summaries'
    end
  end

  resources :categories, only: [] do
    member do
      resources :boards, as: :category_boards , only: [:index, :new] do
        collection do
          match "t/:tag_id" => "boards#tag", as: :tag, via: :get
        end
      end
      resources 'summaries', as: :category_summaries, only: [:index] do
        collection do
          match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
        end
      end
    end
  end

  resources :boards, only: [:index, :show, :new, :create]do
    collection do
      match "t/:tag_id" => "boards#tag", as: :tag, via: :get
    end
    member do
      match 'comments/:num' => "boards#comments", as: :comments, via: :get
      match 'websites/:num' => "boards#websites", as: :websites, via: :get
      match 'images/:num' => "boards#images", as: :images, via: :get
      match 'movies/:num' => "boards#movies", as: :movies, via: :get
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
  end

  resources :comments, only: [:show,:create] do
    member do
      post :good
      post :bad
      post :ng, :action => :add_ng
      delete :ng, :action => :remove_ng
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
    resources :t, controller: "comment_tags", except: [:index, :edit, :update]
  end

  resources :websites, only: [] do
    member do
      get :thumb
    end
  end

  resources :images, only: [:create] do
    member do
      get :image
      get :thumb
    end
  end

  resources :movies, only: [] do
    member do
      get :animation
      get :thumb
    end
  end

  resources :summaries, except: [:new, :destroy] do
    collection do
      match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
      match 'new/:board_id' => 'summaries#new', via: :get, as: :new
      post 'items'
    end
  end

  resources :favorites, only: [:index, :destroy] do
    collection do
      get 'boards'
      get 'summaries'
      post 'boards', action: :create_board
      post 'summaries', action: :create_summary
      delete 'boards/:id', action: :destroy_board
      delete 'summaries/:id', action: :destroy_summary
    end
  end

  scope 'my' do
    get 'boards', controller: "histories", action: "my_boards", as: :my_boards
    get 'comments', controller: "histories", action: "my_comments", as: :my_comments
    get 'summaries', controller: "histories", action: "my_summaries", as: :my_summaries
  end

  scope 'histories' do
    get 'boards', controller: "histories", action: "boards", as: :boards_history
    get 'summaries', controller: "histories", action: "summaries", as: :summaries_history
  end

  resource :ng_list, only: [:show]
  resource :check_list, only: [:show]
  resources :tags, only: [] do
    collection do
      get 'board'
      get 'summary'
      get 'observe', action: :observe
    end
  end

  root :to => 'top#index'

  match '*a', :to => 'application#error_404'

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

  before_filter :authenticate_user!

  def my_boards
    @boards = current_user.boards.order_by(:created_at.desc).page(params[:page]).per(20)
  end

  def my_comments
    @comments = current_user.comments.order_by(:created_at.desc).page(params[:page]).per(20)
  end

  def my_summaries
    @summaries = current_user.summaries.order_by(:created_at.desc).page(params[:page]).per(20)
  end

  def boards
    @boards = current_user.refer_history.boards.page(params[:page]).per(20)
  end

  def summaries
    @summaries = current_user.refer_history.summaries.page(params[:page]).per(20)
  end

end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/boards.html.erb
<h1><%= current_user.name %>さんのスレ参照履歴</h1>
<hr>
<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#boards-histories" data-toggle="tab">スレッド</a></li>
  <li><%= link_to "まとめ", summaries_history_path %></li>
</ul>

<div class="clearfix tab-content">
  <div id="boards-histories" class="tab-pane active" style="margin-left:15px;">
    <table class="table table-striped">
      <thead>
        <tr>
          <td>スレッドタイトル</td>
          <td>参照日時</td>
        </tr>
      </thead>
      <tbody>
      <% @boards.each do |board| %>
        <tr>
          <td>
          <%= link_to board_path(id: board["id"]) do %>
            <%= board["title"] %>
          <% end %>
          </td>
          <td>
            <%=l Time.zone.at(board["refered_at"].to_i) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<hr>
<div align="center">
  <%= paginate @boards %>
</div>

app/views/histories/my_boards.html.erb
<h1><%= current_user.name %>さんの立てたスレッド一覧</h1>
<hr>
<div class="clearfix">
  <%= render partial: "boards/board", collection: @boards, as: :board %>
</div>
<hr>
<div align="center">
  <%= paginate @boards %>
</div>

app/views/histories/my_comments.html.erb
<h1><%= current_user.name %>さんのレス一覧</h1>
<hr>
<div class="clearfix">
<% @comments.each do |comment| %>
  スレッド「<%= link_to comments_board_path(id: comment.board.id, num: "#{comment.num}-") do %>
    <%= comment.board.title %>
  <% end %>」より
  <%= render partial: "comments/comment", locals: {comment:comment, hash_id_map: nil, valid_control: false} %>
<% end %>
</div>
<hr>
<div align="center">
  <%= paginate @comments %>
</div>

app/views/histories/my_summaries.html.erb
<h1><%= current_user.name %>さんのまとめ一覧</h1>
<hr>
<div class="clearfix">
  <%= render partial: "summaries/summary", collection: @summaries, as: :summary %>
</div>
<hr>
<div align="center">
<%= paginate @summaries %>
</div>

app/views/histories/summaries.html.erb
<h1><%= current_user.name %>さんのまとめ参照履歴</h1>
<hr>
<ul class="nav nav-tabs" id="myTab">
  <li><%= link_to "スレッド", boards_history_path %></li>
  <li class="active"><a href="#summary-histories" data-toggle="tab">まとめ</a></li>
</ul>

<div class="clearfix tab-content">
  <div id="summary-histories" class="tab-pane active" style="margin-left:15px;">
    <table class="table table-striped">
      <thead>
        <tr>
          <td>まとめタイトル</td>
          <td>参照日時</td>
        </tr>
      </thead>
      <tbody>
      <% @summaries.each do |summary| %>
        <tr>
          <td>
          <%= link_to summary_path(id: summary["id"]) do %>
            <%= summary["title"] %>
          <% end %>
          </td>
          <td>
            <%=l Time.zone.at(summary["refered_at"].to_i) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<hr>
<div align="center">
  <%= paginate @summaries %>
</div>