config/routes.rb
MatomeChannel::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :members, only: [] do
    member do
      get "board_favorites"
      get "summary_favorites" 
      get 'boards'
      get 'summaries'
    end
  end

  resources :categories, only: [] do
    member do
      resources :boards, as: :category_boards , only: [:index, :new] do
        collection do
          match "t/:tag_id" => "boards#tag", as: :tag, via: :get
        end
      end
      resources 'summaries', as: :category_summaries, only: [:index] do
        collection do
          match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
        end
      end
    end
  end

  resources :boards, only: [:index, :show, :new, :create]do
    collection do
      match "t/:tag_id" => "boards#tag", as: :tag, via: :get
    end
    member do
      match 'comments/:num' => "boards#comments", as: :comments, via: :get
      match 'websites/:num' => "boards#websites", as: :websites, via: :get
      match 'images/:num' => "boards#images", as: :images, via: :get
      match 'movies/:num' => "boards#movies", as: :movies, via: :get
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
  end

  resources :comments, only: [:show,:create] do
    member do
      post :good
      post :bad
      post :ng, :action => :add_ng
      delete :ng, :action => :remove_ng
      post :tag, :action => :add_tag
      delete :tag, :action => :remove_tag
    end
    resources :t, controller: "comment_tags", except: [:index, :edit, :update]
  end

  resources :websites, only: [] do
    member do
      get :thumb
    end
  end

  resources :images, only: [:create] do
    member do
      get :image
      get :thumb
    end
  end

  resources :movies, only: [] do
    member do
      get :animation
      get :thumb
    end
  end

  resources :summaries, except: [:new, :destroy] do
    collection do
      match "t/:tag_id" => "summaries#tag", as: :tag, via: :get
      match 'new/:board_id' => 'summaries#new', via: :get, as: :new
      post 'items'
    end
  end

  resources :favorites, only: [:index, :destroy] do
    collection do
      get 'boards'
      get 'summaries'
      post 'boards', action: :create_board
      post 'summaries', action: :create_summary
      delete 'boards/:id', action: :destroy_board
      delete 'summaries/:id', action: :destroy_summary
    end
  end

  scope 'my' do
    get 'boards', controller: "histories", action: "my_boards", as: :my_boards
    get 'comments', controller: "histories", action: "my_comments", as: :my_comments
    get 'summaries', controller: "histories", action: "my_summaries", as: :my_summaries
  end

  scope 'histories' do
    get 'boards', controller: "histories", action: "boards", as: :boards_history
    get 'summaries', controller: "histories", action: "summaries", as: :summaries_history
  end

  resource :ng_list, only: [:show]
  resource :check_list, only: [:show]
  resources :tags, only: [] do
    collection do
      get 'board'
      get 'summary'
      get 'observe', action: :observe
    end
  end

  root :to => 'top#index'

  match '*a', :to => 'application#error_404'

end

app/models/user.rb
class User
  include ::AbstractUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter, :facebook, :google_oauth2]

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  # fixed handle name
  field :use_fix_handle_name, :type => Boolean, :default => false

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  ## Omni
  field :uid, type: String
  field :name, type: String
  field :provider, type: String

  #relations
  has_one :check_list
  has_one :ng_list
  has_one :refer_history
  has_many :comments
  has_many :boards
  has_many :summaries
  has_many :board_favorites
  has_many :summary_favorites

  #callbacks
  after_create :create_check_list
  after_create :create_ng_list
  after_create :create_refer_history

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
      end
    end
  end


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    user ||= User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         password:Devise.friendly_token[0,20])
    user
  end


  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    user ||= User.create(name:auth.info.nickname,
                         provider:auth.provider,
                         uid:auth.uid,
                         password:Devise.friendly_token[0,20])
    user
  end

  def self.find_for_google_oauth2(auth, signed_in_resource=nil)
    p auth
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    user ||= User.create(name: auth.info.name,
             password: Devise.friendly_token[0,20],
             provider: auth.provider,
             uid: auth.uid
            )
    user
  end

  def email_required?
    super && provider.blank?
  end

  def get_ng_list
    self.ng_list.ng_list
  end

  def get_check_list
    self.check_list.check_list
  end

  def add_ng_list comment
    cl = self.ng_list
    cl.ng_list[comment.hash_id.to_s] = true
    cl.save
  end

  def remove_ng_list comment
    cl = self.ng_list
    cl.unset("ng_list.#{comment.hash_id.to_s}")
  end

  def add_check_list comment, val=1
    uc = self.check_list
    uc.check_list[comment.id.to_s] = val
    uc.save
  end

  def ng? comment
    NgList.where(user_id: self.id, "ng_list.#{comment.hash_id}" => true).any?
  end

  def checked? comment
    CheckList.where(user_id: self.id, "check_list.#{comment.id}".to_sym.ne => nil).any?
  end

  def create_check_list
    CheckList.new {|uc|uc.user = self}.save
  end

  def create_ng_list
    NgList.new {|uc|uc.user = self}.save
  end

  def create_refer_history
    ReferHistory.new {|uc|uc.user = self}.save
  end

  def favorite? object
    case object
    when Board
      self.board_favorites.where(:board_id => object.id).first
    when Summary
      self.summary_favorites.where(:summary_id => object.id).first
    else
      false
    end
  end

  def mine? object
    case object
    when Summary
      object.user == self
    else
      false
    end
  end

  def fixed_handle_name
    self.use_fix_handle_name ? self.name : ''
  end
end

app/controllers/tags_controller.rb
# -*- coding: utf-8 -*-
class TagsController < ApplicationController

  def board
    get_tags BoardTag
  end

  def summary
    get_tags SummaryTag
  end

  def observe
    @tag_name = params[:tag]
    @items = []
    if !@tag_name.blank? && !@tag_name.include?(",")
      @comment_tag = CommentTag.find_or_create_by name: params[:tag]
      @board_tag = BoardTag.find_or_create_by name: params[:tag]
      @summary_tag = SummaryTag.find_or_create_by name: params[:tag]
      @items = @comment_tag.comments.desc(:updated_at).limit(20).to_a
      @items += @board_tag.boards.desc(:updated_at).limit(20).to_a
      @items += @summary_tag.summaries.where(publish: true).desc(:updated_at).limit(20).to_a
      @items.sort!{|a,b|b.updated_at <=> a.updated_at}[0...20]
    elsif @tag_name.blank?
      @error = "タグが指定されていません"
    else
      @error = "タグは1つしか指定出来ません。"
    end
  end

  private

  def get_tags target
    @tags = target.where(:used_count.gt => 0)
    case params[:sort]
    when "use"
      @tags = @tags.order_by(used_count: :desc, created_at: :desc)
    else
      @tags = @tags.order_by(created_at: :desc)
    end
    @tags = @tags.page(params[:page]).per(50)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_add_board_tag.html.erb
<div class='observe_item add_board_tag clearfix'>
  <div class="header">
    <span class="label label-add-board-tag">スレッドタグ追加</span>
    <% board.tags.each do |t|%>
      <span class="badge badge-inverse"><i class="icon-tag icon-white"></i><%= t.name %></span>
    <% end %>
    <span class="title"><%= link_to board.title, board_path(board) %></span>
  </div>
  <div class="content">
    <%= render partial: "tags/comment", locals: {comment: board.first_comment} %>
  </div>
</div>

app/views/tags/_add_comment_tag.html.erb
<div class='observe_item add_comment_tag clearfix'>
  <div class="header">
    <span class="label label-add-comment-tag">コメントタグ追加</span>
    <% comment.board.tags.each do |t|%>
      <span class="badge badge-inverse"><i class="icon-tag icon-white"></i><%= t.name %></span>
    <% end %> 
    <span class="title"><%= link_to comment.board.title, board_path(comment.board) %></span>
  </div>
  <div class="content">
    <%= render partial: "tags/comment", locals: {comment: comment} %>
  </div>
</div>

app/views/tags/_comment.html.erb
<div id='comment-<%= comment.id %>' class='comment clearfix well well-small'>
  <div class='clearfix comment-header'>
    <div class="btn btn-primary">
      <strong class="comment-num"><%= comment.num %></strong>
    </div>
    <span class="comment-name"><strong>名前:</strong>
      <span ><%= comment.name %></span>
    </span>
    <div class="clearfix pull-right">
      <span class="comment-posted-at"><strong>投稿:</strong>
        <%=l comment.created_at %>
      </span>&nbsp;
      <span><strong>ID:</strong>
        <%= comment.hash_id %>
      </span>
    </div> 
    <div class='clearfix comment-tags'>
      <% if comment.tags.any? %>
      <strong class="pull-left">タグ:</strong>
      <div class="clearfix pull-left summary-tag-list">
        <% comment.tags.each do |tag| %>
        <div class='btn-group pull-left'>
          <%= link_to tag_summaries_path(tag), class: "btn btn-inverse btn-mini" do %>
            <i class='icon-tag icon-white'></i> <strong><%= tag.name %></strong>
          <% end %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="clearfix comment-body">
    <%= html_body comment %>
  </div>
  <div class="comment-websites clearfix">
    <%= render partial: 'websites/thumb', collection: comment.websites, as: :website %>
  </div>
  <div class="comment-images clearfix">
    <%= render partial: 'images/thumb', collection: comment.images, as: :image %>
  </div>
  <div class="comment-movies clearfix">
    <%= render partial: 'movies/thumb', collection: comment.movies, as: :movie %>
  </div>
  <div class="clearfix pull-right comment-footer">
    <div class="label label-info label-small">
      <i class='icon-thumbs-up icon-white'></i> ｲｲﾈ!
      <span class="badge badge-info"><%= comment.good %></span>
    </div>
    <div class="label label-important label-small">
      <i class='icon-thumbs-down icon-white'></i> ｲｸﾅｲ!
      <span class="badge badge-important"><%= comment.bad %></span>
    </div>
  </div>
  <br/>
</div>

app/views/tags/_new_board.html.erb
<div class='observe_item new_board clearfix'>
  <div class="header">
    <span class="label label-new-board">新規スレッド</span>
    <% board.tags.each do |t|%>
      <span class="badge badge-inverse"><i class="icon-tag icon-white"></i><%= t.name %></span>
    <% end %>
    <span class="title"><%= link_to board.title, board_path(board) %></span>
  </div>
  <div class="content">
    <%= render partial: "tags/comment", locals: {comment: board.first_comment} %>
  </div>
</div>

app/views/tags/_new_comment.html.erb
<div class='observe_item new_comment clearfix'>
  <div class="header">
    <span class="label label-new-comment">新規コメント</span>
    <% comment.board.tags.each do |t|%>
      <span class="badge badge-inverse"><i class="icon-tag icon-white"></i><%= t.name %></span>
    <% end %> 
    <span class="title"><%= link_to comment.board.title, board_path(comment.board) %></span>
  </div>
  <div class="content">
    <%= render partial: "tags/comment", locals: {comment: comment} %>
  </div>
</div>

app/views/tags/_new_summary.html.erb
<div class='observe_item new_board clearfix'>
  <div class="header">
    <span class="label label-new-summary">新規まとめ</span>
    <% summary.tags.each do |t|%>
      <span class="badge badge-inverse"><i class="icon-tag icon-white"></i><%= t.name %></span>
    <% end %> 
    <span class="title"><%= link_to summary.title, summary_path(summary) %></span>
  </div>
  <div class="content">
    <%= render partial: "tags/summary_notify", locals: {summary: summary} %>
  </div>
</div>

app/views/tags/_search.html.erb
<form  class="form-search" action="<%= observe_tags_path %>" method="get">
  <div class="input-append">
    <input type="text" name="tag" class="span2 search-query" value="<%= tag %>">
    <button type="submit" class="btn">タグ検索</button>
  </div>
</form>

app/views/tags/_summary_notify.html.erb
<div class='summary-notify clearfix well well-small'>
  <div class='clearfix comment-header'>
  </div>
  <div class="clearfix comment-body">
    <%= raw summary.description.gsub(/\r\n|\n/m, "<br/>") %>
  </div>
  <br/>
</div>

app/views/tags/_update_summary.html.erb
<div class='observe_item new_board clearfix'>
  <div class="header">
    <span class="label label-update-summary">まとめ更新</span>
    <% summary.tags.each do |t|%>
      <span class="badge badge-inverse"><i class="icon-tag icon-white"></i><%= t.name %></span>
    <% end %> 
    <span class="title"><%= link_to summary.title, summary_path(summary) %></span>
  </div>
  <div class="content">
    <%= render partial: "tags/summary_notify", locals: {summary: summary} %>
  </div>
</div>

app/views/tags/board.html.erb
<% content_for :content_head do %>
<div class="content-header navbar navbar-static-top" style="margin-top:-20px;margin-bottom:10px;">
  <div class="navbar-inner" class="clearfix" style="padding-bottom:0">
    <div class="container">
      <h3>タグ一覧</h3>
      <ul id="board-tab" class="nav nav-tabs" style="width:100%">
        <li class='active'>
          <%= link_to "スレッド", "#" %>
        </li>
        <li>
          <%= link_to "まとめ", summary_tags_path %>
        </li>
        <div class="pull-right">
          <div class="btn-group">
            <button class="btn">並び順</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li>
                <%= link_to '新着順', board_tags_path(type: @type) %>
              </li>
              <li>
                <%= link_to '人気順', board_tags_path(sort: :use, type: @type) %>
              </li>
            </ul>
          </div>
          <%= link_to "タグを監視する。", observe_tags_path, class: "btn btn-primary" %>
        </div>
      </ul>
    </div>
  </div>
</div>
<% end %>
<div class="container">
<% if @tags.present? %>
  <ul class="thumbnails">
    <% @tags.each do |tag| %>
      <li class="">
        <span class="board-tag btn btn-inverse btn-large" data-url="<%= tag_boards_path(tag) %>">
          <i class="icon-tag icon-white"></i>
          <strong class="title"><%= tag.name %> (<%= tag.used_count %>)</strong>
        </span>
        <div class="popover-content" style="display:none;">
          <h4>人気のスレッド</h4>
          <% if tag.board_ids.size > 0 %>
            <% tag.popular_boards.each do |board| %>
            <div class="thread-content well well-small span2">
              <div class="total">
                <span class="badge board-score" title="スコア">
                  <i class='icon-star icon-white'></i>
                  <strong><%= board.score %></strong>
                </span>
                <span class="badge res-count" title="レス数">
                  <i class='icon-pencil icon-white'></i>
                  <strong><%= board.count %></strong>
                </span>
                <span class="badge favorites-count" title="お気に入り登録数">
                  <i class='icon-heart icon-white'></i>
                  <strong><%= board.favorites.count %></strong>
                </span>
              </div>
              <h4 class="title">
                <%= link_to board.title.to_s.cut(50), board, title:  board.title  %>
              </h4>
              <%= link_to board_path(board), class: :thumbnail do %>
                <%= image_tag thumbnail_path(board.thumbnail) %>
              <% end %>
            </div>
            <% end %>
          <% else %>
            スレッドがありません。
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
  <div align="center">
    <%= paginate @tags %>
  </div>
<% else %>
  タグが存在しません。
<% end %>
</div>

app/views/tags/observe.html.erb
<% content_for :content_head do %>
<div class="content-header navbar navbar-static-top" style="margin-top:-20px;margin-bottom:10px;">
  <div class="navbar-inner" class="clearfix" style="padding-bottom:0">
    <div class="container">
      <div class="tag-observer-header">
        <h1><%= @tag_name %>の検索結果</h1>
        <div class="pull-right">
          <%= render partial: "tags/search", locals: {tag: @tag_name } %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<div id="recv_items" class="container">
<% if @error %>
  <div class="alert alert-error alert-block">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= @error %>
  </div> 
<% else %>
  <%= hidden_field_tag :summary_tag_id, @summary_tag.id %>
  <%= hidden_field_tag :comment_tag_id, @comment_tag.id %>
  <%= hidden_field_tag :board_tag_id, @board_tag.id %>
<% end %> 
<% @items.each do |item|%>
  <% case item %>
  <% when Comment %>
    <%= render partial: "tags/new_comment", locals: {comment: item }%>
  <% when Board %>
    <%= render partial: "tags/new_board", locals: {board: item }%>
  <% when Summary %>
    <%= render partial: "tags/new_summary", locals: {summary: item }%>
  <% end %>
<% end %>
</div>

app/views/tags/summary.html.erb
<% content_for :content_head do %>
<div class="content-header navbar navbar-static-top" style="margin-top:-20px;margin-bottom:10px;">
  <div class="navbar-inner" class="clearfix" style="padding-bottom:0">
    <div class="container">
      <h3>タグ一覧</h3>
      <ul id="summary-tab" class="nav nav-tabs" style="width:100%">
        <li>
          <%= link_to "スレッド", board_tags_path %>
        </li>
        <li class='active'>
          <%= link_to "まとめ", "#" %>
        </li>
        <div class="pull-right">
          <div class="btn-group">
            <button class="btn">並び順</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li>
                <%= link_to '新着順', summary_tags_path(type: @type) %>
              </li>
              <li>
                <%= link_to '人気順', summary_tags_path(sort: :use, type: @type) %>
              </li>
            </ul>
          </div>
          <%= link_to "タグを監視する。", observe_tags_path, class: "btn btn-primary" %>
        </div>
      </ul>
    </div>
  </div>
</div>
<% end %>
<div class="container">
<% if @tags.present? %>
  <ul class="thumbnails">
    <% @tags.each do |tag| %>
      <li class="">
        <span class="summary-tag btn btn-inverse btn-large" data-url="<%= tag_summaries_path(tag) %>">
          <i class="icon-tag icon-white"></i>
          <strong class="title"><%= tag.name %> (<%= tag.used_count %>)</strong>
        </span>
        <div class="popover-content" style="display:none;">
          <h4>人気のまとめ</h4>
          <% if tag.summary_ids.size > 0 %>
            <% tag.popular_summaries.each do |summary| %>
            <div class="thread-content well well-small span2">
              <div class="total">
                <span class="badge summary-score" title="ビュー数">
                  <i class='icon-eye-open icon-white'></i>
                  <strong><%= summary.refered_count %></strong>
                </span>
                <span class="badge favorites-count" title="お気に入り登録数">
                  <i class='icon-heart icon-white'></i>
                  <strong><%= summary.favorites.count %></strong>
                </span>
              </div>
              <h4 class="title">
                <%= link_to summary.title.to_s.cut(50), summary, title:  summary.title  %>
              </h4>
              <%= link_to summary_path(summary), class: :thumbnail do %>
                <%= image_tag thumbnail_path(summary.thumbnail) %>
              <% end %>
            </div>
            <% end %>
          <% else %>
            スレッドがありません。
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
  <div align="center">
    <%= paginate @tags %>
  </div>
<% else %>
  タグが存在しません。
<% end %>
</div>